### PR TITLE
[13.0][TEST] contract: Recurring level on contract

### PR DESCRIPTION
**Pull request by rousseldenis**
This is for testing purpose in order to highlight problem.

@pedrobaeza @sbejaoui

### CODE REVIEW

**Comment by rousseldenis** [comment]
I did a workaround on the second commit. The recurring_next_date has to be recomputed in order to get good values.

**Comment by sbejaoui** [comment]
The `recurring_next_date` compute in contract level consider the the oldest date from contract line. This make sense in case of 'recurrence at line level' is checked as we want that the system invoice the oldest line before.

In case of 'recurrence at contract level', the `recurring_next_date` must consider the most recent date to be able to invoice all lines at once.

**Comment by victoralmau** [comment]
I think that it is not necessary because this method `_prepare_recurring_invoices_values` finally call `_update_recurring_next_date` (and it compute field).

But maybe is interesting to Pedro because he know exactly all code and wouldl be necessary, please comment about it in https://github.com/OCA/contract/pull/533 (with suggestion comment for example).

Thank you a lot for this information!!

**Comment by rousseldenis** [comment]
> I think that it is not necessary because this method `_prepare_recurring_invoices_values` finally call `_update_recurring_next_date` (and it compute field).
> 
> But maybe is interesting to Pedro because he know exactly all code and wouldl be necessary, please comment about it in [OCA#533](https://github.com/OCA/contract/pull/533) (with suggestion comment for example).
> 
> Thank you a lot for this information!!

The problem is the way ORM has changed in v13. As some fields are not pure computed ones, that's the problem (in my test, without the call to _compute_recurring_next_date(), the flush() which represent the save in the interface, will trigger the error - try it).

**Comment by victoralmau** [comment]
> > I think that it is not necessary because this method `_prepare_recurring_invoices_values` finally call `_update_recurring_next_date` (and it compute field).
> > But maybe is interesting to Pedro because he know exactly all code and wouldl be necessary, please comment about it in [OCA#533](https://github.com/OCA/contract/pull/533) (with suggestion comment for example).
> > Thank you a lot for this information!!
> 
> The problem is the way ORM has changed in v13. As some fields are not pure computed ones, that's the problem (in my test, without the call to _compute_recurring_next_date(), the flush() which represent the save in the interface, will trigger the error - try it).

Thanks for the explanation, i will test it now

**Comment by victoralmau** [comment]
I checked now, and this is my comments about it:

- I have apply this changes previously: https://github.com/OCA/contract/pull/533#pullrequestreview-509486009.
- With this test apply (https://github.com/Tecnativa/contract/pull/3/commits/caa40ed0e9ebc70831a75c4535899f6b8bf8afdd) i haven't any error (maybe previous change "prevent" show error). Although is true that `recurring_next_date` don't change (and it is an error). 
It's not necessary but some validations about check `recurring_next_date` that expected will clarify error (if executed today, `recurring_next_date` is + `recurring_interval` `recurring_rule_type`, maybe `_prepare_value_for_stop` function return "expected date")
- With this change apply (https://github.com/Tecnativa/contract/pull/3/commits/d1322a0867e7d215aa71ff61a5da1b773fce3b58) `recurring_next_date` correctly change and previous test work fine.

**Summary**:
This change is necessary to apply (i will suggested it in https://github.com/OCA/contract/pull/533) to improve code but IMO my suggestion https://github.com/Tecnativa/contract/pull/3/commits/caa40ed0e9ebc70831a75c4535899f6b8bf8afdd (or something similar) too prevent error when add more lines and previously some invoices have created.

**Comment by rousseldenis** [comment]
> I checked now, and this is my comments about it:
> 
> * I have apply this changes previously: [OCA#533 (review)](https://github.com/OCA/contract/pull/533#pullrequestreview-509486009).
> * With this test apply ([caa40ed](https://github.com/Tecnativa/contract/commit/caa40ed0e9ebc70831a75c4535899f6b8bf8afdd)) i haven't any error (maybe previous change "prevent" show error). Although is true that `recurring_next_date` don't change (and it is an error).
>   It's not necessary but some validations about check `recurring_next_date` that expected will clarify error (if executed today, `recurring_next_date` is + `recurring_interval` `recurring_rule_type`, maybe `_prepare_value_for_stop` function return "expected date")
> * With this change apply ([d1322a0](https://github.com/Tecnativa/contract/commit/d1322a0867e7d215aa71ff61a5da1b773fce3b58)) `recurring_next_date` correctly change and previous test work fine.
> 
> **Summary**:
> This change is necessary to apply (i will suggested it in [OCA#533](https://github.com/OCA/contract/pull/533)) to improve code but IMO my suggestion [caa40ed](https://github.com/Tecnativa/contract/commit/caa40ed0e9ebc70831a75c4535899f6b8bf8afdd) (or something similar) too prevent error when add more lines and previously some invoices have created.

So, do you want me to change the commits messages to more permanent ones and merge them in the PR ?

**Comment by victoralmau** [comment]
> > I checked now, and this is my comments about it:
> > 
> > * I have apply this changes previously: [OCA#533 (review)](https://github.com/OCA/contract/pull/533#pullrequestreview-509486009).
> > * With this test apply ([caa40ed](https://github.com/Tecnativa/contract/commit/caa40ed0e9ebc70831a75c4535899f6b8bf8afdd)) i haven't any error (maybe previous change "prevent" show error). Although is true that `recurring_next_date` don't change (and it is an error).
> >   It's not necessary but some validations about check `recurring_next_date` that expected will clarify error (if executed today, `recurring_next_date` is + `recurring_interval` `recurring_rule_type`, maybe `_prepare_value_for_stop` function return "expected date")
> > * With this change apply ([d1322a0](https://github.com/Tecnativa/contract/commit/d1322a0867e7d215aa71ff61a5da1b773fce3b58)) `recurring_next_date` correctly change and previous test work fine.
> > 
> > **Summary**:
> > This change is necessary to apply (i will suggested it in [OCA#533](https://github.com/OCA/contract/pull/533)) to improve code but IMO my suggestion [caa40ed](https://github.com/Tecnativa/contract/commit/caa40ed0e9ebc70831a75c4535899f6b8bf8afdd) (or something similar) too prevent error when add more lines and previously some invoices have created.
> 
> So, do you want me to change the commits messages to more permanent ones and merge them in the PR ?

Yes, i think that it's a good idea (in https://github.com/OCA/contract/pull/533)

**Comment by rousseldenis** [comment]
@pedrobaeza @victoralmau @sbejaoui This one is ready to be merged in PR's branch.

**Comment by rousseldenis** [comment]
@pedrobaeza Maybe you could activate travis here to check before merge ?

**Comment by pedrobaeza** [comment]
I'm cherry-picking the commit to see in main branch

**Comment by rousseldenis** [comment]
> I'm cherry-picking the commit to see in main branch

Wait, pre-commit fails. I'll push one new

**Comment by rousseldenis** [comment]
This one is correct

**Comment by pedrobaeza** [comment]
Pushed to main branch, so closing here. With that is everything correct or anything more is missing?

**Comment by rousseldenis** [comment]
> Pushed to main branch, so closing here. With that is everything correct or anything more is missing?

For the bug revealed in discussion, from my point of view it's ok.

**Pull request closed without merging**
